# Generated by Django 3.1.7 on 2021-06-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='tipo_usuario',
        ),
    ]
